package view;

import controller.ControllerComponentes;
import controller.ControllerHistoricoComponente;
import controller.ControllerLogin;
import controller.ControllerProcessos;
import controller.ControllerUsuarioMaquina;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Mattos/ Raylane Fernandes
 */
public class TelaInit extends javax.swing.JFrame {

    ControllerHistoricoComponente controllerHistoricoComponente = new ControllerHistoricoComponente();
    ControllerProcessos controllerProcessos = new ControllerProcessos();
    ControllerComponentes controllerComponentes = new ControllerComponentes();

    /**
     * Creates new form TelaInit
     */
    public TelaInit() {
        initComponents();
        //Colocando cor no fundo da página;
        getContentPane().setBackground(Color.decode("#080425"));

        // Variaveis para adicionar "favicon" na barra superior da página;
        URL caminhoImagem = this.getClass().getClassLoader().getResource("tela-login-rxmonitoramento.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImagem);
        setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(8, 4, 37));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                userLogout(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela-login-rxmonitoramento.png"))); // NOI18N
        jLabelLogo.setRequestFocusEnabled(false);
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(20, 0, 450, 480);

        setSize(new java.awt.Dimension(447, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userLogout(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_userLogout
        ControllerUsuarioMaquina usuarioMaquina = new ControllerUsuarioMaquina();
        try {
            usuarioMaquina.insertUsuarioMaquinaLogout();
        } catch (UnknownHostException ex) {
            Logger.getLogger(TelaInit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_userLogout

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
